# Generated by Django 6.0.4 on 2026-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='preview_image',
            field=models.ImageField(blank=True, editable=False, upload_to='materials/previews/'),
        ),
    ]
